/**
 * build-tokens.js
 * Reads tokens.json (W3C Design Tokens format) and generates
 * static/tokens.css containing resolved CSS custom properties.
 *
 * Run automatically via the `prebuild` npm script.
 */

const fs   = require('fs');
const path = require('path');

const tokensPath = path.join(__dirname, '..', 'tokens.json');
const outputPath = path.join(__dirname, '..', 'static', 'tokens.css');

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

// ── Step 1: Flatten nested token tree → { 'color.brand.primary': '#4D9DA8', ... }

function flatten(obj, prefix) {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue; // skip metadata keys
    const p = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$value' in val) {
      result[p] = val.$value;
    } else if (val && typeof val === 'object') {
      Object.assign(result, flatten(val, p));
    }
  }
  return result;
}

// ── Step 2: Resolve aliases — {color.brand.primary} → actual value

function resolveAliases(flat) {
  const resolved = {};
  for (const [key, val] of Object.entries(flat)) {
    if (typeof val === 'string' && /^\{.+\}$/.test(val)) {
      const ref = val.slice(1, -1);
      resolved[key] = flat[ref] !== undefined ? flat[ref] : val;
    } else {
      resolved[key] = val;
    }
  }
  return resolved;
}

// ── Step 3: Format values for CSS

function formatValue(val) {
  if (Array.isArray(val)) {
    // Font family stack — quote names that contain spaces
    return val.map(v => (/\s/.test(v) ? `"${v}"` : v)).join(', ');
  }
  if (val && typeof val === 'object') {
    // Transition shorthand
    if ('duration' in val) {
      return `${val.duration} ${val.timingFunction}${val.delay && val.delay !== '0ms' ? ' ' + val.delay : ''}`;
    }
  }
  return String(val);
}

// ── Step 4: Generate CSS custom property name

function toCssVar(tokenPath) {
  return '--token-' + tokenPath.replace(/\./g, '-');
}

// ── Run

const flat     = flatten(tokens);
const resolved = resolveAliases(flat);

const lines = [
  '/* Auto-generated by scripts/build-tokens.js — do not edit directly */',
  ':root {',
  ...Object.entries(resolved).map(
    ([key, val]) => `  ${toCssVar(key)}: ${formatValue(val)};`
  ),
  '}',
  '',
];

fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`[tokens] Generated ${outputPath} (${Object.keys(resolved).length} tokens)`);
